# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['gy2', 'foo', 'gy']

# %% ../nbs/00_core.ipynb 2
def gy2():
    print("GY2")

# %% ../nbs/00_core.ipynb 4
def foo(): pass

# %% ../nbs/00_core.ipynb 5
#| echo: true
def gy():
    print("Hello, GY!")
